begin;
set local search_path = public, extensions;
select plan(30);
select has_table('public', 'broadcast_delivery_queue', 'durable channel queues exist');
select ok(not has_table_privilege('anon', 'public.broadcast_delivery_queue', 'select'), 'queues are private');
select ok(not has_function_privilege('authenticated', 'public.claim_broadcast_delivery(text,integer)', 'execute'), 'users cannot claim deliveries');
delete from public.broadcast_delivery_queue;
delete from public.operational_incidents;
update public.broadcast_settings set enabled=true;

insert into public.authority_warnings(id, source, received_via, body, severity, commune_codes)
values ('13000000-0000-4000-8000-000000000001', 'test', 'phone', 'test', 'Severe', '{1501}');
insert into public.broadcasts(id, kind, authority_warning_id, severity, commune_codes, push_codes)
values ('13000000-0000-4000-8000-000000000002', 'authority', '13000000-0000-4000-8000-000000000001', 'Severe', '{1501}', '{1501}');
select is((select count(*) from public.broadcast_delivery_queue where broadcast_id='13000000-0000-4000-8000-000000000002'), 2::bigint, 'publication enqueues both channels');
create temporary table claimed as select * from public.claim_broadcast_delivery('fcm', 1);
select is((select count(*) from claimed), 1::bigint, 'FCM claims one job');
select is((select count(*) from public.claim_broadcast_delivery('fcm', 1)), 0::bigint, 'second worker cannot claim live lease');
select is((select count(*) from public.claim_broadcast_delivery('telegram', 1)), 1::bigint, 'other channel can claim independently');
select ok(not public.renew_broadcast_delivery('13000000-0000-4000-8000-000000000002', 'fcm', gen_random_uuid()), 'stale token cannot renew');
select ok(public.finish_broadcast_delivery('13000000-0000-4000-8000-000000000002', 'fcm', (select (job->>'lease_token')::uuid from claimed), null, 'provider_rejected'), 'failure schedules retry');
select is((select count(*) from public.claim_broadcast_delivery('fcm', 1)), 0::bigint, 'backoff prevents immediate retry');
update public.broadcast_delivery_queue set next_attempt_at=now()-interval '1 minute' where channel='fcm';
truncate claimed;
insert into claimed select * from public.claim_broadcast_delivery('fcm', 1);
select ok(public.finish_broadcast_delivery('13000000-0000-4000-8000-000000000002', 'fcm', (select (job->>'lease_token')::uuid from claimed), 1, null), 'successful retry completes');
select is((select count(*) from public.claim_broadcast_delivery('fcm', 1)), 0::bigint, 'terminal success is never reclaimed');
select ok(not public.finish_broadcast_delivery('13000000-0000-4000-8000-000000000002','fcm',(select (job->>'lease_token')::uuid from claimed),9,null), 'completed lease cannot finish twice');
update public.delivery_channel_settings set paused=true where channel='telegram';
select ok(not public.renew_broadcast_delivery('13000000-0000-4000-8000-000000000002','telegram',(select lease_token from public.broadcast_delivery_queue where channel='telegram')), 'pause revokes permission to send on existing lease');
update public.broadcast_delivery_queue set state='pending',lease_token=null,lease_until=null where channel='telegram';
select is((select count(*) from public.claim_broadcast_delivery('telegram',1)),0::bigint,'paused channel cannot claim');
update public.delivery_channel_settings set paused=false;
update public.broadcast_settings set enabled=false;
select is((select count(*) from public.claim_broadcast_delivery('telegram',1)),0::bigint,'global kill switch prevents claims');
update public.broadcast_settings set enabled=true;
truncate claimed;
insert into claimed select * from public.claim_broadcast_delivery('telegram',1);
select ok(public.finish_broadcast_delivery('13000000-0000-4000-8000-000000000002','telegram',(select (job->>'lease_token')::uuid from claimed),null,'budget_exhausted'),'budget continuation releases lease');
select is((select attempts from public.broadcast_delivery_queue where channel='telegram'),1,'budget continuation does not consume a retry');
update public.broadcast_delivery_queue set expires_at=now()-interval '1 minute' where channel='telegram';
select is((select count(*) from public.claim_broadcast_delivery('telegram',1)),0::bigint,'expired alert is never sent');
select is((select state from public.broadcast_delivery_queue where channel='telegram'),'expired','expiry is durable');
select public.refresh_operational_incidents();
select public.refresh_operational_incidents();
select is((select count(*) from public.operational_incidents where contract_key='broadcast_delivery.telegram' and reason_code='delivery_expired' and resolved_at is null),1::bigint,'repeated watchdog run deduplicates incident');
insert into auth.users(id,email) values ('13000000-0000-4000-8000-000000000003','queue-operator@example.invalid');
insert into public.user_roles(user_id,role) values ('13000000-0000-4000-8000-000000000003','operator');
set local role authenticated;
select set_config('request.jwt.claim.sub','13000000-0000-4000-8000-000000000004',true);
select is((select count(*) from public.delivery_queue_health),0::bigint,'ordinary users cannot read queue health');
select is((select count(id) from public.source_gaps),0::bigint,'ordinary users cannot read source gaps');
select ok(not has_column_privilege('authenticated','public.source_gaps','resolved_by_run_id','select'),'run identifiers remain private');
select throws_ok($$select public.set_delivery_channel_paused('fcm',true)$$,'42501','operator_role_required','ordinary user cannot pause');
select set_config('request.jwt.claim.sub','13000000-0000-4000-8000-000000000003',true);
select lives_ok($$select public.set_delivery_channel_paused('fcm',true)$$,'operator can pause');
select lives_ok($$select id,contract_key,data_from,data_through,state,replay_count,detected_at from public.source_gaps$$,'operator can load replay list');
select public.acknowledge_operational_incident(id) from public.operational_incidents where contract_key='broadcast_delivery.telegram' and resolved_at is null;
select is((select count(*) from public.operational_incidents where contract_key='broadcast_delivery.telegram' and acknowledged_at is not null),1::bigint,'operator acknowledges incident');
reset role;
select is((select count(*) from public.admin_audit where actor_user_id='13000000-0000-4000-8000-000000000003' and target_table='delivery_channel_settings' and target_id='fcm' and action='channel.pause'),1::bigint,'pause is audited');
update public.broadcast_delivery_queue set state='delivered' where channel='telegram';
select public.refresh_operational_incidents();
select is((select count(*) from public.operational_incidents where contract_key='broadcast_delivery.telegram' and resolved_at is not null),1::bigint,'recovery resolves preserved incident');
select * from finish();
rollback;
