/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SurvivalRouteRouteImport } from './routes/survival/route'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedBroadcastsRouteImport } from './routes/_authenticated/broadcasts'
import { Route as AuthenticatedModerationRouteImport } from './routes/_authenticated/moderation'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedWebhooksRouteImport } from './routes/_authenticated/webhooks'
import { Route as AuthenticatedZonesRouteImport } from './routes/_authenticated/zones'
import { Route as FireIdRouteImport } from './routes/fire.$id'
import { Route as SurvivalIndexRouteImport } from './routes/survival/index'
import { Route as SurvivalAreasRouteImport } from './routes/survival/areas'
import { Route as SurvivalCheckinRouteImport } from './routes/survival/checkin'
import { Route as SurvivalSosRouteImport } from './routes/survival/sos'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ContributeLanguageLocaleRouteImport } from './routes/contribute_.language.$locale'
import { Route as ApiInternalSourceJobsRunRouteImport } from './routes/api/internal/source-jobs/run'
import { Route as ApiPublicContributeIdeaRouteImport } from './routes/api/public/contribute/idea'
import { Route as ApiPublicContributeMyTranslationsRouteImport } from './routes/api/public/contribute/my-translations'
import { Route as ApiPublicContributeTranslationRouteImport } from './routes/api/public/contribute/translation'
import { Route as ApiPublicContributeVoteRouteImport } from './routes/api/public/contribute/vote'
import { Route as ApiPublicV1IndexRouteImport } from './routes/api/public/v1/index'
import { Route as ApiPublicV1FiresRouteImport } from './routes/api/public/v1/fires'
import { Route as ApiPublicV1RiskRouteImport } from './routes/api/public/v1/risk'
import { Route as ApiPublicV1SourcesRouteImport } from './routes/api/public/v1/sources'
import { Route as ApiPublicV1StatsRouteImport } from './routes/api/public/v1/stats'
import { Route as ApiPublicV1StatusRouteImport } from './routes/api/public/v1/status'
import { Route as ApiPublicV1SubscribeRouteImport } from './routes/api/public/v1/subscribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SurvivalRouteRoute = SurvivalRouteRouteImport.update({
  id: '/survival',
  path: '/survival',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBroadcastsRoute = AuthenticatedBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModerationRoute = AuthenticatedModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWebhooksRoute = AuthenticatedWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZonesRoute = AuthenticatedZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const FireIdRoute = FireIdRouteImport.update({
  id: '/fire/$id',
  path: '/fire/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SurvivalIndexRoute = SurvivalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SurvivalRouteRoute,
} as any)
const SurvivalAreasRoute = SurvivalAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => SurvivalRouteRoute,
} as any)
const SurvivalCheckinRoute = SurvivalCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => SurvivalRouteRoute,
} as any)
const SurvivalSosRoute = SurvivalSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => SurvivalRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ContributeLanguageLocaleRoute =
  ContributeLanguageLocaleRouteImport.update({
    id: '/contribute_/language/$locale',
    path: '/contribute/language/$locale',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalSourceJobsRunRoute =
  ApiInternalSourceJobsRunRouteImport.update({
    id: '/api/internal/source-jobs/run',
    path: '/api/internal/source-jobs/run',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicContributeIdeaRoute = ApiPublicContributeIdeaRouteImport.update({
  id: '/api/public/contribute/idea',
  path: '/api/public/contribute/idea',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContributeMyTranslationsRoute =
  ApiPublicContributeMyTranslationsRouteImport.update({
    id: '/api/public/contribute/my-translations',
    path: '/api/public/contribute/my-translations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicContributeTranslationRoute =
  ApiPublicContributeTranslationRouteImport.update({
    id: '/api/public/contribute/translation',
    path: '/api/public/contribute/translation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicContributeVoteRoute = ApiPublicContributeVoteRouteImport.update({
  id: '/api/public/contribute/vote',
  path: '/api/public/contribute/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1IndexRoute = ApiPublicV1IndexRouteImport.update({
  id: '/api/public/v1/',
  path: '/api/public/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1FiresRoute = ApiPublicV1FiresRouteImport.update({
  id: '/api/public/v1/fires',
  path: '/api/public/v1/fires',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1RiskRoute = ApiPublicV1RiskRouteImport.update({
  id: '/api/public/v1/risk',
  path: '/api/public/v1/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SourcesRoute = ApiPublicV1SourcesRouteImport.update({
  id: '/api/public/v1/sources',
  path: '/api/public/v1/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1StatsRoute = ApiPublicV1StatsRouteImport.update({
  id: '/api/public/v1/stats',
  path: '/api/public/v1/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1StatusRoute = ApiPublicV1StatusRouteImport.update({
  id: '/api/public/v1/status',
  path: '/api/public/v1/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SubscribeRoute = ApiPublicV1SubscribeRouteImport.update({
  id: '/api/public/v1/subscribe',
  path: '/api/public/v1/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/survival': typeof SurvivalRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contribute': typeof ContributeRoute
  '/developers': typeof DevelopersRoute
  '/forecast': typeof ForecastRoute
  '/history': typeof HistoryRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/alerts': typeof AuthenticatedAlertsRoute
  '/broadcasts': typeof AuthenticatedBroadcastsRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/report': typeof AuthenticatedReportRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/webhooks': typeof AuthenticatedWebhooksRoute
  '/zones': typeof AuthenticatedZonesRoute
  '/fire/$id': typeof FireIdRoute
  '/survival/areas': typeof SurvivalAreasRoute
  '/survival/checkin': typeof SurvivalCheckinRoute
  '/survival/sos': typeof SurvivalSosRoute
  '/survival/': typeof SurvivalIndexRoute
  '/contribute/language/$locale': typeof ContributeLanguageLocaleRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/internal/source-jobs/run': typeof ApiInternalSourceJobsRunRoute
  '/api/public/contribute/idea': typeof ApiPublicContributeIdeaRoute
  '/api/public/contribute/my-translations': typeof ApiPublicContributeMyTranslationsRoute
  '/api/public/contribute/translation': typeof ApiPublicContributeTranslationRoute
  '/api/public/contribute/vote': typeof ApiPublicContributeVoteRoute
  '/api/public/v1/fires': typeof ApiPublicV1FiresRoute
  '/api/public/v1/risk': typeof ApiPublicV1RiskRoute
  '/api/public/v1/sources': typeof ApiPublicV1SourcesRoute
  '/api/public/v1/stats': typeof ApiPublicV1StatsRoute
  '/api/public/v1/status': typeof ApiPublicV1StatusRoute
  '/api/public/v1/subscribe': typeof ApiPublicV1SubscribeRoute
  '/api/public/v1/': typeof ApiPublicV1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contribute': typeof ContributeRoute
  '/developers': typeof DevelopersRoute
  '/forecast': typeof ForecastRoute
  '/history': typeof HistoryRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/broadcasts': typeof AuthenticatedBroadcastsRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/report': typeof AuthenticatedReportRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/webhooks': typeof AuthenticatedWebhooksRoute
  '/zones': typeof AuthenticatedZonesRoute
  '/fire/$id': typeof FireIdRoute
  '/survival/areas': typeof SurvivalAreasRoute
  '/survival/checkin': typeof SurvivalCheckinRoute
  '/survival/sos': typeof SurvivalSosRoute
  '/survival': typeof SurvivalIndexRoute
  '/contribute/language/$locale': typeof ContributeLanguageLocaleRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/internal/source-jobs/run': typeof ApiInternalSourceJobsRunRoute
  '/api/public/contribute/idea': typeof ApiPublicContributeIdeaRoute
  '/api/public/contribute/my-translations': typeof ApiPublicContributeMyTranslationsRoute
  '/api/public/contribute/translation': typeof ApiPublicContributeTranslationRoute
  '/api/public/contribute/vote': typeof ApiPublicContributeVoteRoute
  '/api/public/v1/fires': typeof ApiPublicV1FiresRoute
  '/api/public/v1/risk': typeof ApiPublicV1RiskRoute
  '/api/public/v1/sources': typeof ApiPublicV1SourcesRoute
  '/api/public/v1/stats': typeof ApiPublicV1StatsRoute
  '/api/public/v1/status': typeof ApiPublicV1StatusRoute
  '/api/public/v1/subscribe': typeof ApiPublicV1SubscribeRoute
  '/api/public/v1': typeof ApiPublicV1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/survival': typeof SurvivalRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contribute': typeof ContributeRoute
  '/developers': typeof DevelopersRoute
  '/forecast': typeof ForecastRoute
  '/history': typeof HistoryRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/broadcasts': typeof AuthenticatedBroadcastsRoute
  '/_authenticated/moderation': typeof AuthenticatedModerationRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/webhooks': typeof AuthenticatedWebhooksRoute
  '/_authenticated/zones': typeof AuthenticatedZonesRoute
  '/fire/$id': typeof FireIdRoute
  '/survival/areas': typeof SurvivalAreasRoute
  '/survival/checkin': typeof SurvivalCheckinRoute
  '/survival/sos': typeof SurvivalSosRoute
  '/survival/': typeof SurvivalIndexRoute
  '/contribute_/language/$locale': typeof ContributeLanguageLocaleRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/internal/source-jobs/run': typeof ApiInternalSourceJobsRunRoute
  '/api/public/contribute/idea': typeof ApiPublicContributeIdeaRoute
  '/api/public/contribute/my-translations': typeof ApiPublicContributeMyTranslationsRoute
  '/api/public/contribute/translation': typeof ApiPublicContributeTranslationRoute
  '/api/public/contribute/vote': typeof ApiPublicContributeVoteRoute
  '/api/public/v1/fires': typeof ApiPublicV1FiresRoute
  '/api/public/v1/risk': typeof ApiPublicV1RiskRoute
  '/api/public/v1/sources': typeof ApiPublicV1SourcesRoute
  '/api/public/v1/stats': typeof ApiPublicV1StatsRoute
  '/api/public/v1/status': typeof ApiPublicV1StatusRoute
  '/api/public/v1/subscribe': typeof ApiPublicV1SubscribeRoute
  '/api/public/v1/': typeof ApiPublicV1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/survival'
    | '/about'
    | '/auth'
    | '/contribute'
    | '/developers'
    | '/forecast'
    | '/history'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/admin'
    | '/alerts'
    | '/broadcasts'
    | '/moderation'
    | '/report'
    | '/settings'
    | '/team'
    | '/webhooks'
    | '/zones'
    | '/fire/$id'
    | '/survival/areas'
    | '/survival/checkin'
    | '/survival/sos'
    | '/survival/'
    | '/contribute/language/$locale'
    | '/admin/'
    | '/api/internal/source-jobs/run'
    | '/api/public/contribute/idea'
    | '/api/public/contribute/my-translations'
    | '/api/public/contribute/translation'
    | '/api/public/contribute/vote'
    | '/api/public/v1/fires'
    | '/api/public/v1/risk'
    | '/api/public/v1/sources'
    | '/api/public/v1/stats'
    | '/api/public/v1/status'
    | '/api/public/v1/subscribe'
    | '/api/public/v1/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contribute'
    | '/developers'
    | '/forecast'
    | '/history'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/alerts'
    | '/broadcasts'
    | '/moderation'
    | '/report'
    | '/settings'
    | '/team'
    | '/webhooks'
    | '/zones'
    | '/fire/$id'
    | '/survival/areas'
    | '/survival/checkin'
    | '/survival/sos'
    | '/survival'
    | '/contribute/language/$locale'
    | '/admin'
    | '/api/internal/source-jobs/run'
    | '/api/public/contribute/idea'
    | '/api/public/contribute/my-translations'
    | '/api/public/contribute/translation'
    | '/api/public/contribute/vote'
    | '/api/public/v1/fires'
    | '/api/public/v1/risk'
    | '/api/public/v1/sources'
    | '/api/public/v1/stats'
    | '/api/public/v1/status'
    | '/api/public/v1/subscribe'
    | '/api/public/v1'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/survival'
    | '/about'
    | '/auth'
    | '/contribute'
    | '/developers'
    | '/forecast'
    | '/history'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/alerts'
    | '/_authenticated/broadcasts'
    | '/_authenticated/moderation'
    | '/_authenticated/report'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/webhooks'
    | '/_authenticated/zones'
    | '/fire/$id'
    | '/survival/areas'
    | '/survival/checkin'
    | '/survival/sos'
    | '/survival/'
    | '/contribute_/language/$locale'
    | '/_authenticated/admin/'
    | '/api/internal/source-jobs/run'
    | '/api/public/contribute/idea'
    | '/api/public/contribute/my-translations'
    | '/api/public/contribute/translation'
    | '/api/public/contribute/vote'
    | '/api/public/v1/fires'
    | '/api/public/v1/risk'
    | '/api/public/v1/sources'
    | '/api/public/v1/stats'
    | '/api/public/v1/status'
    | '/api/public/v1/subscribe'
    | '/api/public/v1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SurvivalRouteRoute: typeof SurvivalRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContributeRoute: typeof ContributeRoute
  DevelopersRoute: typeof DevelopersRoute
  ForecastRoute: typeof ForecastRoute
  HistoryRoute: typeof HistoryRoute
  PrivacyRoute: typeof PrivacyRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  FireIdRoute: typeof FireIdRoute
  ContributeLanguageLocaleRoute: typeof ContributeLanguageLocaleRoute
  ApiInternalSourceJobsRunRoute: typeof ApiInternalSourceJobsRunRoute
  ApiPublicContributeIdeaRoute: typeof ApiPublicContributeIdeaRoute
  ApiPublicContributeMyTranslationsRoute: typeof ApiPublicContributeMyTranslationsRoute
  ApiPublicContributeTranslationRoute: typeof ApiPublicContributeTranslationRoute
  ApiPublicContributeVoteRoute: typeof ApiPublicContributeVoteRoute
  ApiPublicV1FiresRoute: typeof ApiPublicV1FiresRoute
  ApiPublicV1RiskRoute: typeof ApiPublicV1RiskRoute
  ApiPublicV1SourcesRoute: typeof ApiPublicV1SourcesRoute
  ApiPublicV1StatsRoute: typeof ApiPublicV1StatsRoute
  ApiPublicV1StatusRoute: typeof ApiPublicV1StatusRoute
  ApiPublicV1SubscribeRoute: typeof ApiPublicV1SubscribeRoute
  ApiPublicV1IndexRoute: typeof ApiPublicV1IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survival': {
      id: '/survival'
      path: '/survival'
      fullPath: '/survival'
      preLoaderRoute: typeof SurvivalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/broadcasts': {
      id: '/_authenticated/broadcasts'
      path: '/broadcasts'
      fullPath: '/broadcasts'
      preLoaderRoute: typeof AuthenticatedBroadcastsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderation': {
      id: '/_authenticated/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webhooks': {
      id: '/_authenticated/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AuthenticatedWebhooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zones': {
      id: '/_authenticated/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof AuthenticatedZonesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/fire/$id': {
      id: '/fire/$id'
      path: '/fire/$id'
      fullPath: '/fire/$id'
      preLoaderRoute: typeof FireIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survival/': {
      id: '/survival/'
      path: '/'
      fullPath: '/survival/'
      preLoaderRoute: typeof SurvivalIndexRouteImport
      parentRoute: typeof SurvivalRouteRoute
    }
    '/survival/areas': {
      id: '/survival/areas'
      path: '/areas'
      fullPath: '/survival/areas'
      preLoaderRoute: typeof SurvivalAreasRouteImport
      parentRoute: typeof SurvivalRouteRoute
    }
    '/survival/checkin': {
      id: '/survival/checkin'
      path: '/checkin'
      fullPath: '/survival/checkin'
      preLoaderRoute: typeof SurvivalCheckinRouteImport
      parentRoute: typeof SurvivalRouteRoute
    }
    '/survival/sos': {
      id: '/survival/sos'
      path: '/sos'
      fullPath: '/survival/sos'
      preLoaderRoute: typeof SurvivalSosRouteImport
      parentRoute: typeof SurvivalRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/contribute_/language/$locale': {
      id: '/contribute_/language/$locale'
      path: '/contribute/language/$locale'
      fullPath: '/contribute/language/$locale'
      preLoaderRoute: typeof ContributeLanguageLocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/source-jobs/run': {
      id: '/api/internal/source-jobs/run'
      path: '/api/internal/source-jobs/run'
      fullPath: '/api/internal/source-jobs/run'
      preLoaderRoute: typeof ApiInternalSourceJobsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contribute/idea': {
      id: '/api/public/contribute/idea'
      path: '/api/public/contribute/idea'
      fullPath: '/api/public/contribute/idea'
      preLoaderRoute: typeof ApiPublicContributeIdeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contribute/my-translations': {
      id: '/api/public/contribute/my-translations'
      path: '/api/public/contribute/my-translations'
      fullPath: '/api/public/contribute/my-translations'
      preLoaderRoute: typeof ApiPublicContributeMyTranslationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contribute/translation': {
      id: '/api/public/contribute/translation'
      path: '/api/public/contribute/translation'
      fullPath: '/api/public/contribute/translation'
      preLoaderRoute: typeof ApiPublicContributeTranslationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contribute/vote': {
      id: '/api/public/contribute/vote'
      path: '/api/public/contribute/vote'
      fullPath: '/api/public/contribute/vote'
      preLoaderRoute: typeof ApiPublicContributeVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/': {
      id: '/api/public/v1/'
      path: '/api/public/v1'
      fullPath: '/api/public/v1/'
      preLoaderRoute: typeof ApiPublicV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/fires': {
      id: '/api/public/v1/fires'
      path: '/api/public/v1/fires'
      fullPath: '/api/public/v1/fires'
      preLoaderRoute: typeof ApiPublicV1FiresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/risk': {
      id: '/api/public/v1/risk'
      path: '/api/public/v1/risk'
      fullPath: '/api/public/v1/risk'
      preLoaderRoute: typeof ApiPublicV1RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/sources': {
      id: '/api/public/v1/sources'
      path: '/api/public/v1/sources'
      fullPath: '/api/public/v1/sources'
      preLoaderRoute: typeof ApiPublicV1SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/stats': {
      id: '/api/public/v1/stats'
      path: '/api/public/v1/stats'
      fullPath: '/api/public/v1/stats'
      preLoaderRoute: typeof ApiPublicV1StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/status': {
      id: '/api/public/v1/status'
      path: '/api/public/v1/status'
      fullPath: '/api/public/v1/status'
      preLoaderRoute: typeof ApiPublicV1StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/subscribe': {
      id: '/api/public/v1/subscribe'
      path: '/api/public/v1/subscribe'
      fullPath: '/api/public/v1/subscribe'
      preLoaderRoute: typeof ApiPublicV1SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedBroadcastsRoute: typeof AuthenticatedBroadcastsRoute
  AuthenticatedModerationRoute: typeof AuthenticatedModerationRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedWebhooksRoute: typeof AuthenticatedWebhooksRoute
  AuthenticatedZonesRoute: typeof AuthenticatedZonesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedBroadcastsRoute: AuthenticatedBroadcastsRoute,
  AuthenticatedModerationRoute: AuthenticatedModerationRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedWebhooksRoute: AuthenticatedWebhooksRoute,
  AuthenticatedZonesRoute: AuthenticatedZonesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SurvivalRouteRouteChildren {
  SurvivalAreasRoute: typeof SurvivalAreasRoute
  SurvivalCheckinRoute: typeof SurvivalCheckinRoute
  SurvivalSosRoute: typeof SurvivalSosRoute
  SurvivalIndexRoute: typeof SurvivalIndexRoute
}

const SurvivalRouteRouteChildren: SurvivalRouteRouteChildren = {
  SurvivalAreasRoute: SurvivalAreasRoute,
  SurvivalCheckinRoute: SurvivalCheckinRoute,
  SurvivalSosRoute: SurvivalSosRoute,
  SurvivalIndexRoute: SurvivalIndexRoute,
}

const SurvivalRouteRouteWithChildren = SurvivalRouteRoute._addFileChildren(
  SurvivalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SurvivalRouteRoute: SurvivalRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContributeRoute: ContributeRoute,
  DevelopersRoute: DevelopersRoute,
  ForecastRoute: ForecastRoute,
  HistoryRoute: HistoryRoute,
  PrivacyRoute: PrivacyRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  FireIdRoute: FireIdRoute,
  ContributeLanguageLocaleRoute: ContributeLanguageLocaleRoute,
  ApiInternalSourceJobsRunRoute: ApiInternalSourceJobsRunRoute,
  ApiPublicContributeIdeaRoute: ApiPublicContributeIdeaRoute,
  ApiPublicContributeMyTranslationsRoute:
    ApiPublicContributeMyTranslationsRoute,
  ApiPublicContributeTranslationRoute: ApiPublicContributeTranslationRoute,
  ApiPublicContributeVoteRoute: ApiPublicContributeVoteRoute,
  ApiPublicV1FiresRoute: ApiPublicV1FiresRoute,
  ApiPublicV1RiskRoute: ApiPublicV1RiskRoute,
  ApiPublicV1SourcesRoute: ApiPublicV1SourcesRoute,
  ApiPublicV1StatsRoute: ApiPublicV1StatsRoute,
  ApiPublicV1StatusRoute: ApiPublicV1StatusRoute,
  ApiPublicV1SubscribeRoute: ApiPublicV1SubscribeRoute,
  ApiPublicV1IndexRoute: ApiPublicV1IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
