/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SurvivalRouteRouteImport } from './routes/survival/route'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedModerationRouteImport } from './routes/_authenticated/moderation'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedWebhooksRouteImport } from './routes/_authenticated/webhooks'
import { Route as AuthenticatedZonesRouteImport } from './routes/_authenticated/zones'
import { Route as FireIdRouteImport } from './routes/fire.$id'
import { Route as SurvivalIndexRouteImport } from './routes/survival/index'
import { Route as SurvivalAreasRouteImport } from './routes/survival/areas'
import { Route as SurvivalCheckinRouteImport } from './routes/survival/checkin'
import { Route as SurvivalSosRouteImport } from './routes/survival/sos'
import { Route as ApiPublicCronAlertsRouteImport } from './routes/api/public/cron/alerts'
import { Route as ApiPublicCronIngestRouteImport } from './routes/api/public/cron/ingest'
import { Route as ApiPublicCronRiskRouteImport } from './routes/api/public/cron/risk'
import { Route as ApiPublicV1IndexRouteImport } from './routes/api/public/v1/index'
import { Route as ApiPublicV1FiresRouteImport } from './routes/api/public/v1/fires'
import { Route as ApiPublicV1RiskRouteImport } from './routes/api/public/v1/risk'
import { Route as ApiPublicV1SourcesRouteImport } from './routes/api/public/v1/sources'
import { Route as ApiPublicV1StatsRouteImport } from './routes/api/public/v1/stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SurvivalRouteRoute = SurvivalRouteRouteImport.update({
  id: '/survival',
  path: '/survival',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModerationRoute = AuthenticatedModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWebhooksRoute = AuthenticatedWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZonesRoute = AuthenticatedZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const FireIdRoute = FireIdRouteImport.update({
  id: '/fire/$id',
  path: '/fire/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SurvivalIndexRoute = SurvivalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SurvivalRouteRoute,
} as any)
const SurvivalAreasRoute = SurvivalAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => SurvivalRouteRoute,
} as any)
const SurvivalCheckinRoute = SurvivalCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => SurvivalRouteRoute,
} as any)
const SurvivalSosRoute = SurvivalSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => SurvivalRouteRoute,
} as any)
const ApiPublicCronAlertsRoute = ApiPublicCronAlertsRouteImport.update({
  id: '/api/public/cron/alerts',
  path: '/api/public/cron/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronIngestRoute = ApiPublicCronIngestRouteImport.update({
  id: '/api/public/cron/ingest',
  path: '/api/public/cron/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRiskRoute = ApiPublicCronRiskRouteImport.update({
  id: '/api/public/cron/risk',
  path: '/api/public/cron/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1IndexRoute = ApiPublicV1IndexRouteImport.update({
  id: '/api/public/v1/',
  path: '/api/public/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1FiresRoute = ApiPublicV1FiresRouteImport.update({
  id: '/api/public/v1/fires',
  path: '/api/public/v1/fires',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1RiskRoute = ApiPublicV1RiskRouteImport.update({
  id: '/api/public/v1/risk',
  path: '/api/public/v1/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SourcesRoute = ApiPublicV1SourcesRouteImport.update({
  id: '/api/public/v1/sources',
  path: '/api/public/v1/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1StatsRoute = ApiPublicV1StatsRouteImport.update({
  id: '/api/public/v1/stats',
  path: '/api/public/v1/stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/survival': typeof SurvivalRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/developers': typeof DevelopersRoute
  '/forecast': typeof ForecastRoute
  '/history': typeof HistoryRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/report': typeof AuthenticatedReportRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/webhooks': typeof AuthenticatedWebhooksRoute
  '/zones': typeof AuthenticatedZonesRoute
  '/fire/$id': typeof FireIdRoute
  '/survival/areas': typeof SurvivalAreasRoute
  '/survival/checkin': typeof SurvivalCheckinRoute
  '/survival/sos': typeof SurvivalSosRoute
  '/survival/': typeof SurvivalIndexRoute
  '/api/public/cron/alerts': typeof ApiPublicCronAlertsRoute
  '/api/public/cron/ingest': typeof ApiPublicCronIngestRoute
  '/api/public/cron/risk': typeof ApiPublicCronRiskRoute
  '/api/public/v1/fires': typeof ApiPublicV1FiresRoute
  '/api/public/v1/risk': typeof ApiPublicV1RiskRoute
  '/api/public/v1/sources': typeof ApiPublicV1SourcesRoute
  '/api/public/v1/stats': typeof ApiPublicV1StatsRoute
  '/api/public/v1/': typeof ApiPublicV1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/developers': typeof DevelopersRoute
  '/forecast': typeof ForecastRoute
  '/history': typeof HistoryRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/report': typeof AuthenticatedReportRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/webhooks': typeof AuthenticatedWebhooksRoute
  '/zones': typeof AuthenticatedZonesRoute
  '/fire/$id': typeof FireIdRoute
  '/survival/areas': typeof SurvivalAreasRoute
  '/survival/checkin': typeof SurvivalCheckinRoute
  '/survival/sos': typeof SurvivalSosRoute
  '/survival': typeof SurvivalIndexRoute
  '/api/public/cron/alerts': typeof ApiPublicCronAlertsRoute
  '/api/public/cron/ingest': typeof ApiPublicCronIngestRoute
  '/api/public/cron/risk': typeof ApiPublicCronRiskRoute
  '/api/public/v1/fires': typeof ApiPublicV1FiresRoute
  '/api/public/v1/risk': typeof ApiPublicV1RiskRoute
  '/api/public/v1/sources': typeof ApiPublicV1SourcesRoute
  '/api/public/v1/stats': typeof ApiPublicV1StatsRoute
  '/api/public/v1': typeof ApiPublicV1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/survival': typeof SurvivalRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/developers': typeof DevelopersRoute
  '/forecast': typeof ForecastRoute
  '/history': typeof HistoryRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/moderation': typeof AuthenticatedModerationRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/webhooks': typeof AuthenticatedWebhooksRoute
  '/_authenticated/zones': typeof AuthenticatedZonesRoute
  '/fire/$id': typeof FireIdRoute
  '/survival/areas': typeof SurvivalAreasRoute
  '/survival/checkin': typeof SurvivalCheckinRoute
  '/survival/sos': typeof SurvivalSosRoute
  '/survival/': typeof SurvivalIndexRoute
  '/api/public/cron/alerts': typeof ApiPublicCronAlertsRoute
  '/api/public/cron/ingest': typeof ApiPublicCronIngestRoute
  '/api/public/cron/risk': typeof ApiPublicCronRiskRoute
  '/api/public/v1/fires': typeof ApiPublicV1FiresRoute
  '/api/public/v1/risk': typeof ApiPublicV1RiskRoute
  '/api/public/v1/sources': typeof ApiPublicV1SourcesRoute
  '/api/public/v1/stats': typeof ApiPublicV1StatsRoute
  '/api/public/v1/': typeof ApiPublicV1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/survival'
    | '/about'
    | '/auth'
    | '/developers'
    | '/forecast'
    | '/history'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/alerts'
    | '/moderation'
    | '/report'
    | '/settings'
    | '/team'
    | '/webhooks'
    | '/zones'
    | '/fire/$id'
    | '/survival/areas'
    | '/survival/checkin'
    | '/survival/sos'
    | '/survival/'
    | '/api/public/cron/alerts'
    | '/api/public/cron/ingest'
    | '/api/public/cron/risk'
    | '/api/public/v1/fires'
    | '/api/public/v1/risk'
    | '/api/public/v1/sources'
    | '/api/public/v1/stats'
    | '/api/public/v1/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/developers'
    | '/forecast'
    | '/history'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/alerts'
    | '/moderation'
    | '/report'
    | '/settings'
    | '/team'
    | '/webhooks'
    | '/zones'
    | '/fire/$id'
    | '/survival/areas'
    | '/survival/checkin'
    | '/survival/sos'
    | '/survival'
    | '/api/public/cron/alerts'
    | '/api/public/cron/ingest'
    | '/api/public/cron/risk'
    | '/api/public/v1/fires'
    | '/api/public/v1/risk'
    | '/api/public/v1/sources'
    | '/api/public/v1/stats'
    | '/api/public/v1'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/survival'
    | '/about'
    | '/auth'
    | '/developers'
    | '/forecast'
    | '/history'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/_authenticated/alerts'
    | '/_authenticated/moderation'
    | '/_authenticated/report'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/webhooks'
    | '/_authenticated/zones'
    | '/fire/$id'
    | '/survival/areas'
    | '/survival/checkin'
    | '/survival/sos'
    | '/survival/'
    | '/api/public/cron/alerts'
    | '/api/public/cron/ingest'
    | '/api/public/cron/risk'
    | '/api/public/v1/fires'
    | '/api/public/v1/risk'
    | '/api/public/v1/sources'
    | '/api/public/v1/stats'
    | '/api/public/v1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SurvivalRouteRoute: typeof SurvivalRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  DevelopersRoute: typeof DevelopersRoute
  ForecastRoute: typeof ForecastRoute
  HistoryRoute: typeof HistoryRoute
  PrivacyRoute: typeof PrivacyRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  FireIdRoute: typeof FireIdRoute
  ApiPublicCronAlertsRoute: typeof ApiPublicCronAlertsRoute
  ApiPublicCronIngestRoute: typeof ApiPublicCronIngestRoute
  ApiPublicCronRiskRoute: typeof ApiPublicCronRiskRoute
  ApiPublicV1FiresRoute: typeof ApiPublicV1FiresRoute
  ApiPublicV1RiskRoute: typeof ApiPublicV1RiskRoute
  ApiPublicV1SourcesRoute: typeof ApiPublicV1SourcesRoute
  ApiPublicV1StatsRoute: typeof ApiPublicV1StatsRoute
  ApiPublicV1IndexRoute: typeof ApiPublicV1IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survival': {
      id: '/survival'
      path: '/survival'
      fullPath: '/survival'
      preLoaderRoute: typeof SurvivalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderation': {
      id: '/_authenticated/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webhooks': {
      id: '/_authenticated/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AuthenticatedWebhooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zones': {
      id: '/_authenticated/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof AuthenticatedZonesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/fire/$id': {
      id: '/fire/$id'
      path: '/fire/$id'
      fullPath: '/fire/$id'
      preLoaderRoute: typeof FireIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survival/': {
      id: '/survival/'
      path: '/'
      fullPath: '/survival/'
      preLoaderRoute: typeof SurvivalIndexRouteImport
      parentRoute: typeof SurvivalRouteRoute
    }
    '/survival/areas': {
      id: '/survival/areas'
      path: '/areas'
      fullPath: '/survival/areas'
      preLoaderRoute: typeof SurvivalAreasRouteImport
      parentRoute: typeof SurvivalRouteRoute
    }
    '/survival/checkin': {
      id: '/survival/checkin'
      path: '/checkin'
      fullPath: '/survival/checkin'
      preLoaderRoute: typeof SurvivalCheckinRouteImport
      parentRoute: typeof SurvivalRouteRoute
    }
    '/survival/sos': {
      id: '/survival/sos'
      path: '/sos'
      fullPath: '/survival/sos'
      preLoaderRoute: typeof SurvivalSosRouteImport
      parentRoute: typeof SurvivalRouteRoute
    }
    '/api/public/cron/alerts': {
      id: '/api/public/cron/alerts'
      path: '/api/public/cron/alerts'
      fullPath: '/api/public/cron/alerts'
      preLoaderRoute: typeof ApiPublicCronAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/ingest': {
      id: '/api/public/cron/ingest'
      path: '/api/public/cron/ingest'
      fullPath: '/api/public/cron/ingest'
      preLoaderRoute: typeof ApiPublicCronIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/risk': {
      id: '/api/public/cron/risk'
      path: '/api/public/cron/risk'
      fullPath: '/api/public/cron/risk'
      preLoaderRoute: typeof ApiPublicCronRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/': {
      id: '/api/public/v1/'
      path: '/api/public/v1'
      fullPath: '/api/public/v1/'
      preLoaderRoute: typeof ApiPublicV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/fires': {
      id: '/api/public/v1/fires'
      path: '/api/public/v1/fires'
      fullPath: '/api/public/v1/fires'
      preLoaderRoute: typeof ApiPublicV1FiresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/risk': {
      id: '/api/public/v1/risk'
      path: '/api/public/v1/risk'
      fullPath: '/api/public/v1/risk'
      preLoaderRoute: typeof ApiPublicV1RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/sources': {
      id: '/api/public/v1/sources'
      path: '/api/public/v1/sources'
      fullPath: '/api/public/v1/sources'
      preLoaderRoute: typeof ApiPublicV1SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/stats': {
      id: '/api/public/v1/stats'
      path: '/api/public/v1/stats'
      fullPath: '/api/public/v1/stats'
      preLoaderRoute: typeof ApiPublicV1StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedModerationRoute: typeof AuthenticatedModerationRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedWebhooksRoute: typeof AuthenticatedWebhooksRoute
  AuthenticatedZonesRoute: typeof AuthenticatedZonesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedModerationRoute: AuthenticatedModerationRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedWebhooksRoute: AuthenticatedWebhooksRoute,
  AuthenticatedZonesRoute: AuthenticatedZonesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SurvivalRouteRouteChildren {
  SurvivalAreasRoute: typeof SurvivalAreasRoute
  SurvivalCheckinRoute: typeof SurvivalCheckinRoute
  SurvivalSosRoute: typeof SurvivalSosRoute
  SurvivalIndexRoute: typeof SurvivalIndexRoute
}

const SurvivalRouteRouteChildren: SurvivalRouteRouteChildren = {
  SurvivalAreasRoute: SurvivalAreasRoute,
  SurvivalCheckinRoute: SurvivalCheckinRoute,
  SurvivalSosRoute: SurvivalSosRoute,
  SurvivalIndexRoute: SurvivalIndexRoute,
}

const SurvivalRouteRouteWithChildren = SurvivalRouteRoute._addFileChildren(
  SurvivalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SurvivalRouteRoute: SurvivalRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  DevelopersRoute: DevelopersRoute,
  ForecastRoute: ForecastRoute,
  HistoryRoute: HistoryRoute,
  PrivacyRoute: PrivacyRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  FireIdRoute: FireIdRoute,
  ApiPublicCronAlertsRoute: ApiPublicCronAlertsRoute,
  ApiPublicCronIngestRoute: ApiPublicCronIngestRoute,
  ApiPublicCronRiskRoute: ApiPublicCronRiskRoute,
  ApiPublicV1FiresRoute: ApiPublicV1FiresRoute,
  ApiPublicV1RiskRoute: ApiPublicV1RiskRoute,
  ApiPublicV1SourcesRoute: ApiPublicV1SourcesRoute,
  ApiPublicV1StatsRoute: ApiPublicV1StatsRoute,
  ApiPublicV1IndexRoute: ApiPublicV1IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
